// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A movie suggestion AI agent.
 *
 * - suggestSimilarMovies - A function that suggests similar movies based on a given movie.
 * - SuggestSimilarMoviesInput - The input type for the suggestSimilarMovies function.
 * - SuggestSimilarMoviesOutput - The return type for the suggestSimilarMovies function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const SuggestSimilarMoviesInputSchema = z.object({
  title: z.string().describe('The title of the movie.'),
  genre: z.string().describe('The genre of the movie.'),
  actors: z.string().describe('The main actors in the movie.'),
  keywords: z.string().describe('Keywords describing the movie.'),
});
export type SuggestSimilarMoviesInput = z.infer<typeof SuggestSimilarMoviesInputSchema>;

const SuggestSimilarMoviesOutputSchema = z.object({
  suggestions: z.array(z.string()).describe('A list of similar movie titles.'),
});
export type SuggestSimilarMoviesOutput = z.infer<typeof SuggestSimilarMoviesOutputSchema>;

export async function suggestSimilarMovies(input: SuggestSimilarMoviesInput): Promise<SuggestSimilarMoviesOutput> {
  return suggestSimilarMoviesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestSimilarMoviesPrompt',
  input: {
    schema: z.object({
      title: z.string().describe('The title of the movie.'),
      genre: z.string().describe('The genre of the movie.'),
      actors: z.string().describe('The main actors in the movie.'),
      keywords: z.string().describe('Keywords describing the movie.'),
    }),
  },
  output: {
    schema: z.object({
      suggestions: z.array(z.string()).describe('A list of similar movie titles.'),
    }),
  },
  prompt: `You are a movie expert. Given the following movie details, suggest other similar movies.\n\nTitle: {{{title}}}\nGenre: {{{genre}}}\nActors: {{{actors}}}\nKeywords: {{{keywords}}}\n\nSuggestions:`,
});

const suggestSimilarMoviesFlow = ai.defineFlow<
  typeof SuggestSimilarMoviesInputSchema,
  typeof SuggestSimilarMoviesOutputSchema
>({
  name: 'suggestSimilarMoviesFlow',
  inputSchema: SuggestSimilarMoviesInputSchema,
  outputSchema: SuggestSimilarMoviesOutputSchema,
},
async input => {
  const {output} = await prompt(input);
  return output!;
});
